// prettier-ignore
export const nouns = [
  'Pack',        'Package',     'Page',        'Pain',         'Paint',
  'Painting',    'Pair',        'Panic',       'Paper',        'Parent',
  'Park',        'Parking',     'Part',        'Particular',   'Partner',
  'Party',       'Pass',        'Passage',     'Passenger',    'Passion',
  'Past',        'Path',        'Patience',    'Patient',      'Pattern',
  'Pause',       'Pay',         'Payment',     'Peace',        'Peak',
  'Pen',         'Penalty',     'Pension',     'People',       'Percentage',
  'Perception',  'Performance', 'Period',      'Permission',   'Permit',
  'Person',      'Personal',    'Personality', 'Perspective',  'Phase',
  'Philosophy',  'Phone',       'Photo',       'Phrase',       'Physical',
  'Physics',     'Piano',       'Pick',        'Picture',      'Pie',
  'Piece',       'Pin',         'Pipe',        'Pitch',        'Pizza',
  'Place',       'Plan',        'Plane',       'Plant',        'Plastic',
  'Plate',       'Platform',    'Play',        'Player',       'Pleasure',
  'Plenty',      'Poem',        'Poet',        'Poetry',       'Point',
  'Police',      'Policy',      'Politics',    'Pollution',    'Pool',
  'Pop',         'Population',  'Position',    'Positive',     'Possession',
  'Possibility', 'Possible',    'Post',        'Pot',          'Potato',
  'Potential',   'Pound',       'Power',       'Practice',     'Preference',
  'Preparation', 'Presence',    'Present',     'Presentation', 'President',
  'Press',       'Pressure',    'Price',       'Pride',        'Priest',
  'Primary',     'Principle',   'Print',       'Prior',        'Priority',
  'Private',     'Prize',       'Problem',     'Procedure',    'Process',
  'Produce',     'Product',     'Professional','Professor',    'Profile',
  'Profit',      'Program',     'Progress',    'Project',      'Promise',
  'Promotion',   'Prompt',      'Proof',       'Property',     'Proposal',
  'Protection',  'Psychology',  'Public',      'Pull',         'Punch',
  'Purchase',    'Purple',      'Purpose',     'Push'
]
