name: Push to UoB GitLab

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Push To Gitlab
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        email: ${{ secrets.GITLAB_EMAIL }}
        name: ${{ secrets.GITLAB_NAME }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "${name}"
        git config user.email "${email}"
        git remote set-url origin "https://oauth2:${token}@git-teaching.cs.bham.ac.uk/mod-msc-proj-2021/wxk100.git"
        git push origin master
