name: Integration Tests

on: [deployment_status]

jobs:
  e2e:
    if:
      # Only run on Preview deployments
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
